Adds saveTopic
briangormanly/agora pull request #202
Opened 2022-10-22 19:57 UTC by TylerHernandez

Save topic allows users to update existing and/or create new topics. This holds objects including assessment and activity. MVP for this feature is fully functional.

2022-10-24 11:37 UTC, briangormanly commented on server/controller/apis/topicController.js
> +        topic.id = req.body.id;
This might be to work with the current UI, but are we moving to a model where we are using topicId (entitynameId?)

2022-10-24 19:34 UTC, cmarcusdimarco requested changes
Looks fantastic overall. We should refactor three pieces based on today's class and based on the interaction with the front end.

2022-10-24 19:34 UTC, cmarcusdimarco commented on server/controller/apis/topicController.js
> +                topic.topicHtml = req.body.topicEditor;
This was a really good catch; I was worried that the .ejs files would be sending a field named topicContentHtml, but a review of those files looks like it sends topicHtml as adjusted here. Well done.

2022-10-24 19:34 UTC, cmarcusdimarco commented on server/controller/apis/topicController.js
>          }
Similar to my concern from new lines 254-258, the previous code checked for a field topicActive (see line 87 of client/agora/views/dashboard/partials/topic/edit-topic.ejs). We should leave this check in place to allow the front-end code to remain unchanged.

2022-10-24 19:34 UTC, cmarcusdimarco commented on server/controller/apis/topicController.js
> -        topic.isRequired = ( req.body.isRequired == "on" || req.body.isRequired == true ) ? true : false;
Based on @briangormanly 's feedback in class today, we should leave this intact and adjust at a later time if needed.

2022-10-24 19:34 UTC, cmarcusdimarco commented on server/model/assessment.js
> +    this.isRequired = false;
Based on @briangormanly 's feedback in class today, we should leave this as an empty string and adjust at a later time if needed.

2022-10-27 01:38 UTC, cmarcusdimarco approved these changes
Looks good - thank you for the adjustments, team.

2022-10-27 01:38 UTC, cmarcusdimarco commented on server/model/assessment.js
> +    this.isRequired = "";               // boolean in DB, but leaving as string for now
We can always revert this change once we start implementing assessments in the future if needed as well.

2022-10-30 15:46 UTC, cmarcusdimarco commented
Good updates in 805be4a and 186c9e6. No change in my approval for this PR.

2022-10-30 22:28 UTC, Mike-Volchko approved these changes
Looks good to me. Nice Job!

2022-11-01 12:55 UTC, briangormanly approved these changes
good to go

2022-11-01 12:56 UTC, merged