198 change goal to workspace
briangormanly/agora pull request #208
Opened 2022-10-28 21:28 UTC by JamesVetro

This pull request IS NOT FINISHED. This request needs to be worked on by front end in order to make this work. However, the back end section of this is done, and so it is ready to be pushed to their side.

2022-10-30 15:51 UTC, cmarcusdimarco requested changes
All of the goal -> workspace refactoring looks good at first glance, but this pull request has some additional changes that are not related to the renaming. Please revert the changes to the resource and topic controllers so we can localize those changes to their related issue.

2022-10-30 22:35 UTC, Mike-Volchko requested changes
Please revert the save image changes in all 3 apis.

2022-10-30 22:35 UTC, Mike-Volchko commented on server/controller/apis/resourceController.js
> -                this.saveResourceImage( req, res, resource.id, 'cell-molecule.svg' );
As Marcus suggested. We need to revert these save image changes in resources, topics, and workspaces. They do not relate to this ticket and use the nested if structure that we talked about removing on 10/24.

2022-11-01 13:11 UTC, briangormanly requested changes
Looks like this one might not make the cut for the lint changes.. There are also so conflicts now that other PR's have been merged, make sure to pull main back into this branch / resolve the conflicts before resubmitting.

2022-11-07 13:26 UTC, briangormanly commented
Make sure to pull main into this branch! there are a lot of conflicts that need to be taken care off.

2022-11-16 21:33 UTC, JamesVetro commented
All the changes

2022-11-16 21:33 UTC, closed without merging

2022-11-16 21:33 UTC, JamesVetro commented
The duplication here is to be closed, no further work on this PR needed