Updates resources and goals api to follow api.apiId new name convention
briangormanly/agora pull request #224
Opened 2022-11-08 21:05 UTC by TylerHernandez

2022-11-08 21:12 UTC, Mike-Volchko approved these changes
Looks good.

2022-11-09 15:45 UTC, cmarcusdimarco requested changes
I am all set to approve once notebook-pen.svg is restored.

2022-11-09 15:45 UTC, cmarcusdimarco commented on client/agora/public/assets/uploads/resource/notebook-pen.svg
> -<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 112.83 122.88"><defs><style>.cls-1{fill-rule:evenodd;}</style></defs><title>notebook</title><path class="cls-1" d
This image missing in the PR makes me think we didn't fully resolve the saveImage issue. @Mike-Volchko we should look into this.

2022-11-10 19:26 UTC, cmarcusdimarco commented
@briangormanly ready when you are on this one - don't want to push it through without your review.

2022-11-11 12:56 UTC, briangormanly approved these changes
good to god.

2022-11-11 12:56 UTC, merged