Removed extra 'version' field on GET requests and implemented dynamic incrementing on save
briangormanly/agora pull request #226
Opened 2022-11-08 21:27 UTC by Caleb-Rogers

2022-11-08 21:30 UTC, Mike-Volchko approved these changes
Looks good.

2022-11-09 15:55 UTC, cmarcusdimarco reviewed
Please see the comment on line 172 - I am happy to approve if this is the intended behavior for a reason I don't see, but we should consider the benefits of checking for changes before incrementing version number.

2022-11-09 15:55 UTC, cmarcusdimarco commented on server/controller/apis/goalController.js
> +            goal.goalVersion++;
Looks like the new functionality will increment the version number even if the existing goal is saved with no changes. If this is intentional due to thinking that use case will be very rare, I don't mind approving. However, it looks like checking for changes would be as simple as comparing the existingGoal fields with the goal passed in via the req parameter.

2022-11-13 23:15 UTC, Mike-Volchko commented
Looks like the new changes address @cmarcusdimarco comment. Once this PR is approved by @cmarcusdimarco and @briangormanly we can merge.

2022-11-14 03:08 UTC, briangormanly approved these changes
looks good.

2022-11-14 03:10 UTC, briangormanly requested changes
It looks good but there is a conflict now with main.

2022-11-15 17:49 UTC, Caleb-Rogers commented
Added a couple of commits that fixed some issues and resolved the merge conflicts which were caused by the change from goal.id to goal.goalId. This PR is now ready to merge.

2022-11-16 13:47 UTC, briangormanly approved these changes
Update to date with main, ready to go.

2022-11-16 13:48 UTC, merged